services:
  - type: web
    name: intelligent-sms-summarizer
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    pythonVersion: 3.8.10
